#!/bin/bash
git init -qqq
git remote add origin https://github.com/dtnsolutions/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
