#!/bin/bash
git init -qqq
git remote add origin https://github.com/dtnsolutions/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
rm docker-compose.yml
mv docker-compose.stg.yml docker-compose.yml
rm -rf compose .git
